# Рабочая тетрадь №2

In [1]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler, StandardScaler

### 1.3.1 Задание 

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами.

In [2]:
np.array([[(x + y) % 2 for x in range(9)] for y in range(9)])

array([[0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0]])

### 1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания 
необходимо использовать функцию arrange.

In [3]:
np.array([np.arange(0, 5) for _ in range(5)])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.

In [4]:
np.random.random((3, 3, 3))

array([[[0.96434513, 0.85749524, 0.27053821],
        [0.21644986, 0.68229216, 0.08250954],
        [0.41610945, 0.87883088, 0.60126523]],

       [[0.4745142 , 0.62590903, 0.94890506],
        [0.879023  , 0.2984298 , 0.4204874 ],
        [0.76711694, 0.55453693, 0.78717441]],

       [[0.03274185, 0.19916306, 0.15368702],
        [0.20767858, 0.85001115, 0.77567064],
        [0.41289084, 0.34320754, 0.1702902 ]]])

### 1.3.4 Задание

Создать матрицу с 0 внутри, и 1 на границах.

In [5]:
np.array([[int((x in [0, 14]) or (y in [0, 14])) for x in range(15)] for y in range(15)])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [6]:
arr = np.arange(0, 10)
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.3.6 Задание

Создайте матрицу, выведите ее форму, размер и размерность.

In [7]:
arr = np.random.random(np.full(12, 2))

print("Размерность массива по каждой оси:", arr.shape)
print("Число измерений:", arr.ndim)
print("Колличество элементов:", arr.size)

Размерность массива по каждой оси: (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
Число измерений: 12
Колличество элементов: 4096

### 2.3.1 Задание

Найди евклидово расстояние между двумя Series (точками) a и b, не 
используя встроенную формулу.

In [8]:
from math import sqrt

first_dot = pd.Series([1, 0])
second_dot = pd.Series([0, 1])

s = 0
for dim in range(first_dot.size):
    s += (first_dot.array[dim] - second_dot.array[dim]) ** 2

print(sqrt(s))

1.4142135623730951

### 2.3.2 Задание 

Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данных можно найти 
здесь: https://github.com/akmand/datasets).

In [9]:
url = 'https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/airlines.csv'

df = pd.read_csv(url)

df

       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0           CO     269         SFO       IAH          3    15     205      1
1           US    1558         PHX       CLT          3    15     222      1
2           AA    2400         LAX       DFW          3    20     165      1
3           AA    2466         SFO       DFW          3    20     195      1
4           AS     108         ANC       SEA          3    30     202      0
...        ...     ...         ...       ...        ...   ...     ...    ...
539378      CO     178         OGG       SNA          5  1439     326      0
539379      FL     398         SEA       ATL          5  1439     305      0
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

[539383 rows x 8 columns]

### 2.3.3 Задание

Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7.

#### 2.2.5

Пронализировать характеристики фрейма данных.

In [10]:
df.head(2)

  Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1

In [11]:
df.tail(3)

       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

In [12]:
df.shape

(539383, 8)

In [13]:
df.describe()

,Flight,DayOfWeek,Time,Length,Delay
count,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000
mean,2427.928630,3.929668,802.728963,132.202007,0.445442
std,2067.429837,1.914664,278.045911,70.117016,0.497015
min,1.000000,1.000000,10.000000,0.000000,0.000000
25%,712.000000,2.000000,565.000000,81.000000,0.000000
50%,1809.000000,4.000000,795.000000,115.000000,0.000000
75%,3745.000000,5.000000,1035.000000,162.000000,1.000000
max,7814.000000,7.000000,1439.000000,655.000000,1.000000

#### 2.2.6

Выберите индивидуальные данные или срезы фрейма данных.

In [14]:
df.iloc[1:4]

  Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1

#### 2.2.7

Требуется  отобрать  строки  фрейма  данных  на  основе  некоторого 
условия.

In [15]:
df[df['Airline'] == 'US'].head(2)

   Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1       US    1558         PHX       CLT          3    15     222      1
15      US     498         DEN       CLT          3    55     179      0

### 3.3.2 Задание

Загрузить фрейм данных по ссылке: 
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. 
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования.

In [16]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

iris_df = pd.read_csv(url)

iris_df

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [17]:
length_feature = np.array(iris_df['sepal_length_cm']).reshape(-1,1)

minmax_scale = MinMaxScaler(feature_range = (0, 1))
scaled_sepal_length = minmax_scale.fit_transform(length_feature)
iris_df['sepal_length_cm'] = scaled_sepal_length;

In [18]:
width_feature = np.array(iris_df['sepal_width_cm']).reshape(-1,1)

z_scale = StandardScaler()
scaled_sepal_width = z_scale.fit_transform(width_feature)
iris_df['sepal_width_cm'] = scaled_sepal_width

In [19]:
iris_df

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,0.222222,1.032057,1.4,0.2,setosa
1,0.166667,-0.124958,1.4,0.2,setosa
2,0.111111,0.337848,1.3,0.2,setosa
3,0.083333,0.106445,1.5,0.2,setosa
4,0.194444,1.263460,1.4,0.2,setosa
...,...,...,...,...,...
145,0.666667,-0.124958,5.2,2.3,virginica
146,0.555556,-1.281972,5.0,1.9,virginica
147,0.611111,-0.124958,5.2,2.0,virginica
148,0.527778,0.800654,5.4,2.3,virginica
149,0.444444,-0.124958,5.1,1.8,virginica